spring:
  datasource:
    url: jdbc:mysql://192.168.1.9:3306/jdbc
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    schema:
#      - classpath:department.sql