# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/camunda?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    # 高版本的mysql需要使用com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8085
# camunda config（1.取消租户检查，根据项目需要进行设置，默认会检查租户
#               2.取消自动部署bpm，默认会自动部署）
camunda:
  bpm:
    authorization:
      tenant-check-enabled: false
    auto-deployment-enabled: false
